### ISSUE TITLE
#Final TODO

### ISSUE THREAD

**Issue by PondiB** [jonas-hurst/advanced-tissot#1]
- [x] Automatic circle size
- [x] Automatic circle spacing
- [x] speedup point generation
- [x] edit visualization: classify
- [x] Watermark when loading package
- [x] Named license
- [x] Vignette
